import { NextResponse } from "next/server";
import { User } from "@prisma/client";
import { postUserController } from "./controller";

export async function POST(req: Request) {
    try {
        // Omit the requirement of 'id' field since it's generated by neon.tech
        const userData: Omit<User, "id"> = await req.json();
    
        // controller defined in controller.ts
        const newUser = postUserController(userData);
    
        return NextResponse.json(newUser, { status: 201 });
      } catch (error) {
        throw error; // throws error to the front end for better debugging, swap this out for below code
        // when passing to client
    
        return NextResponse.json(
          { error: "Failed to create user" },
          { status: 500 }
        );
      }
}
