// TESTING COMPONENT

"use client";
import { useState } from "react";
import { updateUser } from "@/lib/api/users";
import { getOneUser} from "@/lib/api/users";
import { User } from "@prisma/client";


const UpdateUserButton = () => {
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
  
    const handleUpdateUser = async () => {
      setLoading(true);
      setError(null);
  
      try {
        await updateUser(new_update);
        getOneUser("user_one")
        console.log("updating one user");
        //console.log(user)
      } catch (err) {
        console.log("error bro");
        setError("Failed to update user by id");
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
  
    return (
      <div>
        <button onClick={handleUpdateUser} disabled={loading}>
          {loading ? "Getting..." : "Update User"}
        </button>
        {error && <p style={{ color: "red" }}>{error}</p>}
      </div>
    );
  };

  export const new_update: User = {
    id: "user_one",
    name: "U1",
    email: "u1@gmail.com",
    role: "Admin",
    createdAt: new Date("2020-01-01T00:00:00.000Z"),  // should be autogenerated
    updatedAt: new Date("2020-01-01T00:00:00.000Z"),
  }
  
  export default UpdateUserButton;